ALTER TABLE Partidos_Tenis ADD CuotaJ1 DECIMAL(18, 2) NULL;
ALTER TABLE Partidos_Tenis ADD CuotaJ2 DECIMAL(18, 2) NULL;
ALTER TABLE Partidos_Tenis ADD ResultadoSets NVARCHAR(MAX) NULL;

ALTER TABLE Equipos ADD ELO_Arcilla INT NULL;
ALTER TABLE Equipos ADD ELO_Pasto INT NULL;
ALTER TABLE Equipos ADD ELO_Dura INT NULL;
