// <auto-generated />
using System;
using BetIQ.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetIQ.API.Migrations
{
    [DbContext(typeof(BetIQContext))]
    [Migration("20260512030935_AddOddsHistory")]
    partial class AddOddsHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BetIQ.API.Models.Equipo", b =>
                {
                    b.Property<string>("NombreEquipo")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Nombre_Equipo");

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deporte");

                    b.Property<int>("EloActual")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Actual");

                    b.Property<int?>("EloArcilla")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Arcilla");

                    b.Property<int?>("EloDura")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Dura");

                    b.Property<int?>("EloPasto")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Pasto");

                    b.HasKey("NombreEquipo");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("BetIQ.API.Models.FutbolMatch", b =>
                {
                    b.Property<int>("ID_Partido")
                        .HasColumnType("int");

                    b.Property<decimal?>("CuotaEmpate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CuotaLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CuotaVisitante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Equipo_Local");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Equipo_Visitante");

                    b.Property<decimal?>("FuerzaAtaqueLocal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Fuerza_Ataque_Local");

                    b.Property<decimal?>("FuerzaAtaqueVisita")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Fuerza_Ataque_Visita");

                    b.Property<decimal?>("FuerzaDefensaLocal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Fuerza_Defensa_Local");

                    b.Property<decimal?>("FuerzaDefensaVisita")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Fuerza_Defensa_Visita");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<string>("Liga")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Partido");

                    b.ToTable("Partidos_Futbol", (string)null);
                });

            modelBuilder.Entity("BetIQ.API.Models.NBAMatch", b =>
                {
                    b.Property<int>("ID_Partido")
                        .HasColumnType("int");

                    b.Property<decimal?>("CuotaLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CuotaVisitante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ELOLocal")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Local");

                    b.Property<int>("ELOVisita")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Visita");

                    b.Property<decimal>("EficienciaDefensivaLocal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Eficiencia_Defensiva_Local");

                    b.Property<decimal>("EficienciaOfensivaLocal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Eficiencia_Ofensiva_Local");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Equipo_Local");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Equipo_Visitante");

                    b.Property<decimal?>("NetRatingLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetRatingVisitante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PromedioPuntosTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Promedio_Puntos_Total");

                    b.Property<int?>("PuntosLocal")
                        .HasColumnType("int")
                        .HasColumnName("Puntos_Local");

                    b.Property<int?>("PuntosVisitante")
                        .HasColumnType("int")
                        .HasColumnName("Puntos_Visitante");

                    b.Property<decimal?>("TrueShootingLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TrueShootingVisitante")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Partido");

                    b.ToTable("Partidos_NBA", (string)null);
                });

            modelBuilder.Entity("BetIQ.API.Models.OddsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CuotaLocalRegistrada")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CuotaVisitanteRegistrada")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsLineaDeCierre")
                        .HasColumnType("bit");

                    b.Property<bool>("EsValueBet")
                        .HasColumnType("bit");

                    b.Property<decimal>("ExpectedValueLocal")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("ExpectedValueVisita")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("ProbabilidadModeloLocal")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("TimestampCaptura")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Odds_History");
                });

            modelBuilder.Entity("BetIQ.API.Models.PartidoMaestro", b =>
                {
                    b.Property<int>("ID_Partido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Partido"));

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Evento")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Partido");

                    b.ToTable("Partidos_Maestro", (string)null);
                });

            modelBuilder.Entity("BetIQ.API.Models.TenisMatch", b =>
                {
                    b.Property<int>("ID_Partido")
                        .HasColumnType("int");

                    b.Property<decimal?>("CuotaJ1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CuotaJ2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EloJugador1")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Jugador_1");

                    b.Property<int?>("EloJugador2")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Jugador_2");

                    b.Property<string>("Jugador1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Jugador_1");

                    b.Property<string>("Jugador2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Jugador_2");

                    b.Property<string>("ResultadoSets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Superficie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Torneo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Partido");

                    b.ToTable("Partidos_Tenis", (string)null);
                });

            modelBuilder.Entity("BetIQ.API.Models.FutbolMatch", b =>
                {
                    b.HasOne("BetIQ.API.Models.PartidoMaestro", "PartidoMaestro")
                        .WithOne("FutbolMatch")
                        .HasForeignKey("BetIQ.API.Models.FutbolMatch", "ID_Partido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartidoMaestro");
                });

            modelBuilder.Entity("BetIQ.API.Models.NBAMatch", b =>
                {
                    b.HasOne("BetIQ.API.Models.PartidoMaestro", "PartidoMaestro")
                        .WithOne("NbaMatch")
                        .HasForeignKey("BetIQ.API.Models.NBAMatch", "ID_Partido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartidoMaestro");
                });

            modelBuilder.Entity("BetIQ.API.Models.TenisMatch", b =>
                {
                    b.HasOne("BetIQ.API.Models.PartidoMaestro", "PartidoMaestro")
                        .WithOne("TenisMatch")
                        .HasForeignKey("BetIQ.API.Models.TenisMatch", "ID_Partido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartidoMaestro");
                });

            modelBuilder.Entity("BetIQ.API.Models.PartidoMaestro", b =>
                {
                    b.Navigation("FutbolMatch");

                    b.Navigation("NbaMatch");

                    b.Navigation("TenisMatch");
                });
#pragma warning restore 612, 618
        }
    }
}
