// <auto-generated />
using System;
using BetIQ.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetIQ.API.Migrations
{
    [DbContext(typeof(BetIQContext))]
    partial class BetIQContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BetIQ.API.Models.Equipo", b =>
                {
                    b.Property<string>("NombreEquipo")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Nombre_Equipo");

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deporte");

                    b.Property<int>("EloActual")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Actual");

                    b.HasKey("NombreEquipo");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("BetIQ.API.Models.NBAMatch", b =>
                {
                    b.Property<int>("ID_Partido")
                        .HasColumnType("int");

                    b.Property<decimal?>("CuotaLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CuotaVisitante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ELOLocal")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Local");

                    b.Property<int>("ELOVisita")
                        .HasColumnType("int")
                        .HasColumnName("ELO_Visita");

                    b.Property<decimal>("EficienciaDefensivaLocal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Eficiencia_Defensiva_Local");

                    b.Property<decimal>("EficienciaOfensivaLocal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Eficiencia_Ofensiva_Local");

                    b.Property<string>("EquipoLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Equipo_Local");

                    b.Property<string>("EquipoVisitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Equipo_Visitante");

                    b.Property<decimal>("PromedioPuntosTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Promedio_Puntos_Total");

                    b.Property<int?>("PuntosLocal")
                        .HasColumnType("int")
                        .HasColumnName("Puntos_Local");

                    b.Property<int?>("PuntosVisitante")
                        .HasColumnType("int")
                        .HasColumnName("Puntos_Visitante");

                    b.HasKey("ID_Partido");

                    b.ToTable("Partidos_NBA", (string)null);
                });

            modelBuilder.Entity("BetIQ.API.Models.PartidoMaestro", b =>
                {
                    b.Property<int>("ID_Partido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Partido"));

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Evento")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Partido");

                    b.ToTable("Partidos_Maestro", (string)null);
                });

            modelBuilder.Entity("BetIQ.API.Models.NBAMatch", b =>
                {
                    b.HasOne("BetIQ.API.Models.PartidoMaestro", "PartidoMaestro")
                        .WithOne("NbaMatch")
                        .HasForeignKey("BetIQ.API.Models.NBAMatch", "ID_Partido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartidoMaestro");
                });

            modelBuilder.Entity("BetIQ.API.Models.PartidoMaestro", b =>
                {
                    b.Navigation("NbaMatch");
                });
#pragma warning restore 612, 618
        }
    }
}
